{"name": "Ошибка при неверном логине или пароле", "status": "passed", "description": "Проверяем, что нельзя авторизоваться с несуществующими учётными данными", "steps": [{"name": "Отправляем запрос с неверным login", "status": "passed", "start": 1755422385770, "stop": 1755422385871}, {"name": "Ожидаем статус 404 и проверяем, что в ответе есть сообщение об ошибке", "status": "passed", "start": 1755422385871, "stop": 1755422385871}], "parameters": [{"name": "field", "value": "'login'"}], "start": 1755422385770, "stop": 1755422385871, "uuid": "320d2627-cc08-4eb9-aa3f-a4e66446266d", "historyId": "10eeebf9c4ddeea748659ca0258aafc3", "testCaseId": "49f68268dab52e6af64f8214b5a5c151", "fullName": "tests.test_auth_courier.TestAuthCourier#test_failure_auth_courier_invalid_data", "labels": [{"name": "feature", "value": "API: Авторизация курьера"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth_courier"}, {"name": "subSuite", "value": "TestAuthCourier"}, {"name": "host", "value": "DESKTOP-RUV96V5"}, {"name": "thread", "value": "12272-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth_courier"}], "titlePath": ["tests", "test_auth_courier.py", "TestAuthCourier"]}