{"name": "Ошибка при неверном пароле", "status": "passed", "description": "Проверяем, что нельзя авторизоваться с несуществующим паролем", "steps": [{"name": "Отправка запроса на авторизацию с несуществующим логином", "status": "passed", "steps": [{"name": "Авторизация курьера", "status": "passed", "parameters": [{"name": "login", "value": "'wayneherrera'"}, {"name": "password", "value": "'none_password'"}], "start": 1755634153467, "stop": 1755634153554}], "start": 1755634153467, "stop": 1755634153554}, {"name": "Проверка статуса ответа: должен быть 404 и в теле ответа есть сообщение об ошибке: \"Учетная запись не найдена\"", "status": "passed", "start": 1755634153554, "stop": 1755634153554}], "start": 1755634153467, "stop": 1755634153555, "uuid": "cdcec9b7-9d54-4829-9cc5-a9ba4f0742aa", "historyId": "244d36b826886a32a0d3a4dcae282523", "testCaseId": "244d36b826886a32a0d3a4dcae282523", "fullName": "tests.test_auth_courier.TestAuthCourier#test_failure_auth_courier_invalid_password", "labels": [{"name": "feature", "value": "API: Авторизация курьера"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth_courier"}, {"name": "subSuite", "value": "TestAuthCourier"}, {"name": "host", "value": "DESKTOP-RUV96V5"}, {"name": "thread", "value": "24996-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth_courier"}], "titlePath": ["tests", "test_auth_courier.py", "TestAuthCourier"]}