{"name": "Ошибка при неверном логине или пароле", "status": "passed", "description": "Проверяем, что нельзя авторизоваться с несуществующими учётными данными", "steps": [{"name": "Отправляем запрос с неверным password", "status": "passed", "start": 1755422386163, "stop": 1755422386254}, {"name": "Ожидаем статус 404 и проверяем, что в ответе есть сообщение об ошибке", "status": "passed", "start": 1755422386254, "stop": 1755422386254}], "parameters": [{"name": "field", "value": "'password'"}], "start": 1755422386163, "stop": 1755422386255, "uuid": "60cf3b61-696f-40b1-9479-45da1cdccc23", "historyId": "6f09d0ac16cbd3a756c2f34ac964996b", "testCaseId": "49f68268dab52e6af64f8214b5a5c151", "fullName": "tests.test_auth_courier.TestAuthCourier#test_failure_auth_courier_invalid_data", "labels": [{"name": "feature", "value": "API: Авторизация курьера"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth_courier"}, {"name": "subSuite", "value": "TestAuthCourier"}, {"name": "host", "value": "DESKTOP-RUV96V5"}, {"name": "thread", "value": "12272-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth_courier"}], "titlePath": ["tests", "test_auth_courier.py", "TestAuthCourier"]}